### ISSUE TITLE
Consider shortcuts for generating columns?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tflearn#4]
(Opening mainly for discussion)

The names used for generating columns are somewhat big and unwieldy, e.g.

```
layers$sparse_column_with_keys(...)
layers$sparse_column_with_hash_bucket(...)
layers$real_valued_column(...)
layers$embedding_column(...)
```

It might be useful to map these to objects using `column_` as the prefix. For example:

```
column_with_keys(...)
column_with_hash_bucket(...)
column_real_valued(...)
column_embedding(...)
column_crossed(...)
```

Is something like this worth considering?

**Comment by terrytangyuan** [comment]
Yes, more generally, this idea should apply to layers, optimizers, metrics, etc., which should mostly be part of rstudio/tensorflow. Feature columns should mostly apply here in tflearn though. @jjallaire What do you think?

**Comment by jjallaire** [comment]
Yes, I agree that feature columns are a tflearn concept and should stay there.
